-- ============================================================
-- Life Growth — Postgres Schema  (DB Version 6)
-- Run once in your Vercel Postgres dashboard or via psql
-- ============================================================

-- Track schema version so the Android app can gate migrations
CREATE TABLE IF NOT EXISTS schema_version (
  version     INTEGER PRIMARY KEY,
  applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Users ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_profile (
  user_id        UUID         PRIMARY KEY,          -- generated by Android app
  username       VARCHAR(64)  NOT NULL UNIQUE,
  password_hash  CHAR(64)     NOT NULL,             -- SHA-256 hex, 64 chars
  level          INTEGER      NOT NULL DEFAULT 1,
  monthly_score  NUMERIC(4,2) NOT NULL DEFAULT 10.0,
  is_logged_in   BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── Daily Usage Stats ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS usage_stats (
  id                  BIGSERIAL    PRIMARY KEY,
  user_id             UUID         NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE,
  stat_date           DATE         NOT NULL,
  screen_time_minutes INTEGER      NOT NULL DEFAULT 0,
  unlock_count        INTEGER      NOT NULL DEFAULT 0,
  idle_worth_score    NUMERIC(4,2) NOT NULL DEFAULT 10.0,
  ai_insight          TEXT,
  synced_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, stat_date)   -- one row per user per day; upsert-safe
);

-- ── Per-App Breakdown ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS app_usage (
  id                  BIGSERIAL    PRIMARY KEY,
  user_id             UUID         NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE,
  stat_date           DATE         NOT NULL,
  app_name            VARCHAR(128) NOT NULL,
  category            VARCHAR(64)  NOT NULL,
  usage_time_minutes  INTEGER      NOT NULL DEFAULT 0,
  synced_at           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, stat_date, app_name)
);

-- ── Indexes ──────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_usage_stats_user_date ON usage_stats (user_id, stat_date DESC);
CREATE INDEX IF NOT EXISTS idx_app_usage_user_date   ON app_usage  (user_id, stat_date DESC);

-- ── Auto-update updated_at ───────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_user_profile_updated_at ON user_profile;
CREATE TRIGGER trg_user_profile_updated_at
  BEFORE UPDATE ON user_profile
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Record schema version
INSERT INTO schema_version (version) VALUES (6)
  ON CONFLICT (version) DO NOTHING;
